//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Election.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectionEntities : DbContext
    {
        public ElectionEntities()
            : base("name=electDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidates> Candidates { get; set; }
        public virtual DbSet<Citizens> Citizens { get; set; }
        public virtual DbSet<PoliticalGroups> PoliticalGroups { get; set; }
        public virtual DbSet<Tokens> Tokens { get; set; }
        public virtual DbSet<Vote> Vote { get; set; }
    }
}
